# Generated by Django 3.2.4 on 2021-07-22 10:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
