# Generated by Django 3.2.4 on 2021-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название тэга'),
        ),
    ]
