# Generated by Django 3.2.4 on 2021-07-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('id', 'title')},
        ),
    ]
