# Generated by Django 3.2.4 on 2021-07-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_thing_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['-date_published'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
    ]
