# Generated by Django 3.2.4 on 2021-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_thing_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['-date_published'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AddField(
            model_name='section',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено ли'),
        ),
        migrations.AddField(
            model_name='thing',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено ли'),
        ),
        migrations.AddField(
            model_name='thingmessage',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено ли'),
        ),
    ]
