# Generated by Django 3.2.4 on 2021-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_alter_thing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён ли'),
        ),
    ]
