# Generated by Django 3.2.4 on 2021-08-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0009_auto_20210722_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена вещи'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('confirmed', 'Подтвержден'), ('completed', 'Выполнен')], max_length=15, verbose_name='Статус заказа')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена сделки')),
                ('status_log', models.JSONField(default=list)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner_thing_deals', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('old_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_owner_thing_deals', to=settings.AUTH_USER_MODEL, verbose_name='Владелец вещи')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='things.thing', verbose_name='Вещь, для которой пишется сообщение')),
            ],
            options={
                'verbose_name': 'Сделки',
                'unique_together': {('old_owner', 'new_owner', 'thing')},
            },
        ),
    ]
