# Generated by Django 3.2.4 on 2021-08-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0009_auto_20210722_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deal', models.DateTimeField(auto_now=True, verbose_name='Дата и время сделки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_thing_transcation', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_thing_transcation', to=settings.AUTH_USER_MODEL, verbose_name='Владелец вещи')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='things.thing', verbose_name='Вещь, для которой пишется сообщение')),
            ],
            options={
                'verbose_name': 'Сделки',
            },
        ),
    ]
