# Generated by Django 3.2.4 on 2021-07-22 10:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_auto_20210722_0746'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='section',
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='thing',
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='thingmessage',
            managers=[
                ('objects_with_deleted', django.db.models.manager.Manager()),
            ],
        ),
    ]
