# Generated by Django 3.2.4 on 2021-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Принят'), ('Confirmed', 'Подтвержден'), ('Paid', 'Оплачивается'), ('Completed', 'Выполнен')], default=None, max_length=15, verbose_name='Статус заказа'),
            preserve_default=False,
        ),
    ]
