# Generated by Django 3.2.4 on 2021-08-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_auto_20210804_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together=set(),
        ),
    ]
