# Generated by Django 3.2.4 on 2021-07-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_thing_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='is_deleted',
        ),
    ]
