# Generated by Django 3.2.4 on 2021-08-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_auto_20210805_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
    ]
