# Generated by Django 3.2.4 on 2021-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена вещи'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status_log',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Принят'), ('Confirmed', 'Подтвержден'), ('Completed', 'Выполнен')], max_length=15, verbose_name='Статус заказа'),
        ),
    ]
