# Generated by Django 3.2.4 on 2021-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0012_auto_20210803_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена сделки'),
        ),
    ]
