# Generated by Django 3.2.4 on 2021-08-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0012_alter_deal_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='status_log',
        ),
    ]
