# Generated by Django 3.2.4 on 2021-08-03 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0013_alter_transaction_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('confirmed', 'Подтвержден'), ('completed', 'Выполнен')], max_length=15, verbose_name='Статус заказа')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена сделки')),
                ('status_log', models.JSONField()),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner_thing_deal', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('old_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_owner_thing_deal', to=settings.AUTH_USER_MODEL, verbose_name='Владелец вещи')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='things.thing', verbose_name='Вещь, для которой пишется сообщение')),
            ],
            options={
                'verbose_name': 'Сделки',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
