# Generated by Django 3.2.4 on 2021-08-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0014_dislike_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'Дизлайк', 'verbose_name_plural': 'Дизлайки'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
