# Generated by Django 3.2.4 on 2021-08-26 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0015_auto_20210826_0803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('owner', 'thing')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'thing')},
        ),
    ]
